export const myProjects = [
  {
    id: 1,
    title: "Leon Website",
    cetegory: "CSS & HTML",
    img: "/images/main/a.png",
    giturl: "https://github.com/tayseer2/HTML---CSS-Leon-Website",
    demo: "https://tayseer2.github.io/HTML---CSS-Leon-Website/",
  },
  {
    id: 2,
    title: "Kasper Website",
    cetegory: "CSS & HTML",
    img: "/images/main/s.png",
    giturl: "https://github.com/tayseer2/HTML-And-CSS-Kasper-Website-Design",
    demo: "https://tayseer2.github.io/HTML-And-CSS-Kasper-Website-Design/",
  },
  {
    id: 3,
    title: "Elrahhal",
    cetegory: "CSS & HTML",
    img: "/images/main/d.png",
    giturl: "https://github.com/tayseer2/HTML-And-CSS-Elrahhal",
    demo: "https://tayseer2.github.io/HTML-And-CSS-Elrahhal/",
  },
  {
    id: 4,
    title: "Elrahhal-v2",
    cetegory: "CSS & HTML",
    img: "/images/main/f.png",
    giturl: "https://github.com/tayseer2/HTML---CSS-Elrahal",
    demo: "https://tayseer2.github.io/HTML---CSS-Elrahal/",
  },
  {
    id: 5,
    title: "QR Code Generator",
    cetegory: "JavaScript",
    img: "/images/main/g.png",
    giturl: "https://github.com/tayseer2/QR-Code-Generator",
    demo: "https://tayseer2.github.io/QR-Code-Generator/",
  },
  {
    id: 6,
    title: "Stop Watch",
    cetegory: "JavaScript",
    img: "/images/main/h.png",
    giturl: "https://github.com/tayseer2/stop-watch",
    demo: "https://tayseer2.github.io/stop-watch/",
  },
  {
    id: 7,
    title: "Password Generator",
    cetegory: "JavaScript",
    img: "/images/main/j.png",
    giturl: "https://github.com/tayseer2/Generate-a-Random-Password",
    demo: "https://tayseer2.github.io/Generate-a-Random-Password/",
  },
  {
    id: 8,
    title: "weather App",
    cetegory: "JavaScript",
    img: "/images/main/k.png",
    giturl: "https://github.com/tayseer2/Weather-App",
    demo: "https://tayseer2.github.io/Weather-App/",
  },
  {
    id: 9,
    title: "tailwindcss desgin",
    cetegory: "React & Tailwindcss",
    img: "/images/main/l.png",
    giturl: "https://github.com/tayseer2/React-Tailwindcss",
    demo: "https://tailwindcss-desgin.netlify.app/",
  },
  {
    id: 10,
    title: "Prayer Times",
    cetegory: "React & Tailwindcss",
    img: "/images/main/z.png",
    giturl: "https://github.com/tayseer2/prayer-times",
    demo: "https://prayer-times-v0.netlify.app/",
  },
  {
    id: 11,
    title: "E-Commerce",
    cetegory: "React & Tailwindcss",
    img: "/images/main/x.png",
    giturl: "https://github.com/tayseer2/Shope-v2",
    demo: "https://shope-v2.netlify.app/",
  },
];
