export const myProjects = [
    {
      id: 1,
      title: "Leon Website",
      cetegory: "CSS & HTML",
      img: "/src/images/main/a.png",
      giturl: "https://github.com/tayseer2/HTML---CSS-Leon-Website",
      demo: "https://tayseer2.github.io/HTML---CSS-Leon-Website/",
    },
    {
      id: 2,
      title: "Kasper Website",
      cetegory: "CSS & HTML",
      img: "/src/images/main/s.png",
      giturl: "https://github.com/tayseer2/HTML-And-CSS-Kasper-Website-Design",
      demo: "https://tayseer2.github.io/HTML-And-CSS-Kasper-Website-Design/",
    },
    {
      id: 3,
      title: "Elrahhal",
      cetegory: "CSS & HTML",
      img: "/src/images/main/d.png",
      giturl: "https://github.com/tayseer2/HTML-And-CSS-Elrahhal",
      demo: "https://tayseer2.github.io/HTML-And-CSS-Elrahhal/",
    },
    {
      id: 4,
      title: "Elrahhal-v2",
      cetegory: "CSS & HTML",
      img: "/src/images/main/f.png",
      giturl: "https://github.com/tayseer2/HTML---CSS-Elrahal",
      demo: "https://tayseer2.github.io/HTML---CSS-Elrahal/",
    },
    {
      id: 5,
      title: "QR Code Generator",
      cetegory: "JavaScript",
      img: "/src/images/main/g.png",
      giturl: "https://github.com/tayseer2/QR-Code-Generator",
      demo: "https://tayseer2.github.io/QR-Code-Generator/",
    },
    {
      id: 6,
      title: "Stop Watch",
      cetegory: "JavaScript",
      img: "/src/images/main/h.png",
      giturl: "https://github.com/tayseer2/stop-watch",
      demo: "https://tayseer2.github.io/stop-watch/",
    },
    {
      id: 7,
      title: "Password Generator",
      cetegory: "JavaScript",
      img: "/src/images/main/j.png",
      giturl: "https://github.com/tayseer2/Generate-a-Random-Password",
      demo: "https://tayseer2.github.io/Generate-a-Random-Password/",
    },
    {
      id: 8,
      title: "weather App",
      cetegory: "JavaScript",
      img: "/src/images/main/k.png",
      giturl: "https://github.com/tayseer2/Weather-App",
      demo: "https://tayseer2.github.io/Weather-App/",
    },
  ];
  